# Generated by Django 2.2.2 on 2019-07-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
