# Generated by Django 2.2.1 on 2019-07-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190702_1301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moradorpagoucaixa',
            unique_together={('morador', 'caixa')},
        ),
    ]
